data = ['A.K. Joshi English Medium School',
        'Activity High School',
        'Aditya Birla World Academy',
        'Ahmedabad International School (AIS)',
        'Ajmera Global School',
        'Akshara International School',
        'Alexandra Girls English Institution',
        'Aman Setu - My School - Lohegaon',
        'American School of Bombay (ASB)',
        'Amulakh Amichand International School',
        'Anand Niketan, Satellite',
        'Anand Niketan, Shilaj',
        'Apeejay School Nerul',
        'Apple Global School',
        'Army Public School',
        'Army Public School Ahmedabad',
        'Arya Vidya Mandir, Bandra E (AVM)',
        'Arya Vidya Mandir, Bandra W (AVM)',
        'Arya Vidya Mandir, Juhu (AVM)',
        'Ascend International School',
        'Ashoka Universal School Nasik',
        'Asia English School',
        'Aspee Nutan Academy',
        'Atomic Energy Central School No 1, Anushaktinagar',
        'Auxilium Convent High School',
        'Ava Bai Petit School',
        'Avalon Heights International School',
        'Bai Avabai Framji Petit Girls High School',
        'Baikabibai Balvatika',
        'Bal Bharti Public School Kharghar',
        'Balmohan Vidyamandir',
        'Banyan Tree International School',
        'BD Somani International School',
        'Beacon High School',
        'Besant Montessori School',
        'Bhaktivedanta Swami Mission School',
        'Billabong High International School, Thane',
        'Billabong High International School, Malad',
        'Birla School, Kalyan',
        'Blue Ridge Public School',
        'Bombay Cambridge',
        'Bombay International School',
        'Bombay Scottish School, Mahim',
        'Bombay Scottish School, Powai',
        'Bright International School',
        'Bright Start International School',
        'C P Goenka International School, Pune',
        'C.N.M School (CNMS)',
        'Caelum High School',
        'Calorex Public School',
        'Cambridge School, Kandivali E',
        'Campion School',
        'Canossa High School',
        'Carmelite Convent English',
        'Cathedral and John Connon Infant',
        'Cathedral and John Connon School',
        'Childrens Academy, Ashok Nagar',
        'Childrens Academy, Malad',
        'Childrens Academy, Thakur Complex',
        'Christ Church School, Byculla',
        'City International School, Andheri',
        'City International School, Aundh',
        'City International School, Kothrud',
        'City International School, Satara Road',
        'Clara Global School',
        'D G Khetan International School',
        'D. Y. Patil International School, Nerul',
        'D. Y. Patil International School, Worli',
        'Daffodils High Public School',
        'DAV International School',
        'DAV International School, Mulund',
        'DAV Public School, Airoli',
        'DAV Public School, Aundh',
        'DAV Public School, Nerul',
        'DAV Public School, Panvel',
        'DAV Public School, Thane',
        'Delhi Public School, Gandhinagar (DPS)',
        'Delhi Public School, Nerul (DPS)',
        'Delhi Public School, Nyati County (DPS)',
        'Dhirubhai Ambani International School',
        'Diamond Jubilee High School',
        'Divine Child International School',
        'Divyajyot School',
        'Don Bosco High School, Borivali',
        'Don Bosco High School, Matunga',
        'Don Bosco International School, Matunga',
        'Delhi Public School, Bopal (DPS)',
        'Dr. Pillai Global Academy, Borivali',
        'Dr. Sarvepalli Radhakrishnan Vidyalaya, Borivali',
        'Dr. Sarvepalli Radhakrishnan Vidyalaya, Malad',
        'E Joseph School',
        'Ecole Mondiale World School, Juhu',
        'Eklavya School',
        'EuroKids, Lokhandwala',
        'EuroSchool, Airoli',
        'EuroSchool, Thane',
        'EuroSchool, Undri',
        'EuroSchool, Wakad',
        'Father Agnel Multipurpose School',
        'Fazlani International School',
        'Fravashi International Academy',
        'G D Somani Memorial School',
        'G G International School (GGIS)',
        'Garodia International Centre for Learning',
        'Global Indian International School, Ahmedabad (GIIS)',
        'Gloria Convent High School',
        'Gokuldham High School',
        'Goldcrest High, Vashi',
        'Gopi Birla Memorial School',
        'Greenlawns High School, Warden Road',
        'Greenlawns School, Worli',
        'Gundecha Education Academy ',
        'Gurukul ',
        'Gyaanam Preparatory School',
        'Hiranandani Foundation School, Powai',
        'Hiranandani Foundation School, Thane',
        'Holy Family school',
        'Hutchings High School and Junior College',
        'HVB Global Academy',
        'IES Manik Vidyamandir, Bandra W',
        'IES New English School',
        'IES Orion School, Dadar',
        'Indira Kids, Baner',
        'Indira National School, Wakad',
        'Indus International School, Pune',
        'J.B. Petit High School for Girls',
        'Jamnabai Narsee School',
        'Jankidevi Public School',
        'Jasudben M. L. School',
        'JB Vachha High School',
        'JBCN International School, Borivali',
        'JBCN International School, Oshiwara',
        'JBCN International School, Parel',
        'Jnana Prabhodini Navanagar Vidyalaya',
        'Jyotirmay International School, Pune',
        'Kapol Vidyanidhi International School',
        'Kashinath Palod Public School, Jalgaon',
        'KGT International School',
        'Khyati World School',
        'Kohinoor Blossoms',
        'Kohinoor International',
        'Kookaburra Learning Center',
        'Kothari International School',
        'Lakshaya PreSchool',
        'Lakshdham High School, (Goregaon E)',
        'Lakshdham Playmate Preschool',
        'Lakshya International School',
        'Leapbridge School, Kalyani Nagar',
        'Lilavatibai Podar High School, Santacruz W',
        'Little Bite Play School',
        'Little Flower Pre-Primary School',
        'Lodha World School, Palava',
        'Lok Puram Public School',
        'Lokhandwala Foundation',
        'Lokseva E School',
        'LR & SM Vissanji Academy',
        'Mahatma Gandhi International School',
        'Manav Mandir',
        'Maneckji Cooper Education Trust School',
        'Mar Gregorios Nursery & Kindergarten',
        'Marble Arch School',
        'MET Rishikul Vidyalaya',
        'Millennium National School',
        'MKVV International Vidyalaya',
        'MLSR International School',
        'Mount Carmel High School, Navrangpura',
        'Mount Litera School International',
        'N L Dalmia High School',
        'Nahar International School',
        'Nalanda Public School',
        'Narayana E-Techno School',
        'Navy Children School, Colaba',
        'NES International School, Dombivli',
        'NES International School, Mulund',
        'NES National Public School, Mulund',
        'Neuron Labs',
        'New Alpha Academy, Colaba',
        'New Horizon Scholars School, Airoli',
        'New India School, Bhusari Colony',
        'Nirma Vidyavihar',
        'Nirman High School, Vastrapur',
        'North Point School, Koparkhairane',
        'NSS Hill Spring International School',
        'Oberoi International School',
        'Omkar International School',
        'Orchids, The  International School, Kurla',
        'Orchids, The  International School, Masjid Bunder',
        'Orchids, The  International School, Thane',
        'Oxford Public School ',
        'P. Jog Education Trust, Mayur Colony',
        'P.G. Garodia School',
        'Panbai International School',
        'Parle Tilak Vidyalaya (ICSE)',
        'Parle Tilak Vidyalaya (SSC)',
        'Pawar Public School, Bhandup (PPS)',
        'Pawar Public School, Chandivali (PPS)',
        'Pawar Public School, Hadapsar (PPS)',
        'Pawar Public School, Kandivali (PPS)',
        'Pawar Public School, Dombivali (PPS)',
        'Pawar Public School, Hinjewadi (PPS)',
        'Pawar Public School, Nanded City (PPS)',
        'Phoenix World School',
        'Podar - ORT International school, Worli',
        'Podar International (CBSE), Thane',
        'Podar International (CIE), Thane',
        'Podar International School (CBSE), Powai',
        'Podar International School (CBSE), Wagholi',
        'Podar International School (CIE), Powai',
        'Podar International School (ICSE), Kalyan',
        'Podar International School (ICSE), Nerul',
        'Podar International School IB, Khar (W)',
        'Podar International School IGCSE, Khar (W)',
        'Podar Jumbo Kids, Aundh',
        'Podar Jumbo Kids, Powai',
        'Prakash Higher Secondary School',
        'Prime Academy',
        'Primrose Pre Primary School',
        'Queen Mary School',
        'R.N. Podar, Santacruz',
        'Radcliffe School, Kharghar',
        'Rajhans Vidyalaya',
        'Ram Ratna International School, Thane',
        'Ramniwas Bajaj English High School, Malad W',
        'Ramsheth Thakur Public School, Kharghar',
        'RBK International Academy, Chembur',
        'RBK School, Mira Road',
        'Redbricks School',
        'Reliance Foundation School, Koparkhairane',
        'RIMS International School, Undri',
        'Rosary School',
        'Rose Manor International School',
        'Rustomjee Cambridge International School, Dahisar (RCIS)',
        'Rustomjee Cambridge International School, Thane (RCIS)',
        'Rustomjee Cambridge International School, Virar (RCIS)',
        'Rustomjee Troopers, Dahisar',
        'Ryan Christian School (ICSE), Borivali W',
        'Ryan Christian School (ICSE), Navi Mumbai',
        'Ryan Global School, Andheri',
        'Ryan Global School, Chembur',
        'Ryan Global School, Kharghar',
        'Ryan International School (CBSE), Kandivali E',
        'Ryan International School (CBSE), Malad',
        'Ryan International School (CBSE), Nalasopara',
        'Ryan International School (ICSE), Chembur E',
        'Ryan International School (ICSE), Goregaon E',
        'Ryan International School (ICSE), Malad W',
        'Ryan International School (ICSE), Nerul',
        'Ryan International School, Bavdhan',
        'Ryan International School, Nasik',
        'S E International',
        'S M Shetty International School',
        'S.D.E.M.School, Kharadi',
        'S.L. Porwal English Medium High School',
        'S.P.M. School',
        'Sacred Heart Boys High School, Santacruz W',
        'Sacred Heart High School, Vashi',
        'Sacred Heart School, Kalyan',
        'Saint Joseph High School',
        'Sanskar - A Child Development Centre',
        'Sansrikti School, Bhukum (Chandani Chowk)',
        'Sansrikti School, NIBM (Undri)',
        'Sansrikti School, Wagholi',
        'Sapling Nursery',
        'Saraswati Mandir High School CBSE',
        'Sardar Vallabhbhai Patel Vidyalaya',
        'Sas Billabong High School, Mahim',
        'Savitri Devi Hariram Agarwal International School',
        'The Scholar High School',
        'Seth Juggilal Poddar Academy',
        'Sevasadan English Medium School',
        'Seven Isles Cambridge International School',
        'Sharda Mandir High School, Girgaon',
        'Sheth Vidyamandir English High School, Vasai',
        'Shishuvan',
        'Shivashish School',
        'Shree Madhavrao Bhagwat High School',
        'Shree Narayanana Guru Central School',
        'Shreyas School',
        'Shri Balaji International School',
        'SIES High School Matunga',
        'Singapore International',
        'Sinhgad Spring Dale High School',
        'Sister Nivedita English Medium School Dombivali',
        'Smt RSB Arya Vidya Mandir',
        'Smt. K C. Gandhi School',
        'Smt. Sulochanadevi Singhania School',
        'SNBP International School, Rahatni',
        'SPM English School',
        'Sri Ma Vidyalaya',
        'Sri Sri Ravi Shankar Bal Mandir',
        'Sri Sri Ravi Shankar Vidya Mandir',
        'Sri Sri Ravi Shankar Vidya Mandir - Borivali East',
        'Sri Sri Ravi Shankar Vidya Mandir - Mulund west',
        'Sri Vani Vidhyashala High School',
        'St Francis ICSE School, Borivali',
        'St Helenas School',
        'St Josephs School, Malad',
        'St Lawrence High School, Borivali Mumbai',
        'St Marys School ICSE, Koparkhairane',
        'St Teresas Convent High School',
        'St Xaviers School',
        'St. Annes Girls High School, Fort',
        'St. Anthonys High School, Sakinaka',
        'St. Gregorios School, Chembur',
        'St. Johns Universal School',
        'St. Josephs Convent School, Bandra',
        'St. Kabir (Little Scholars - Drive In- New)',
        'St. Kabir School Naranpura',
        'St. Kabir School, Drive In New',
        'St. Kabir School, Drive In Old',
        'St. Kabir School, Navarangpura',
        'St. Marys School',
        'St. Marys School ICSE, Mazagoan',
        'St. Marys School, Pune',
        'St. Peters High School',
        'St. Thomas English School',
        'St. Vincents High School',
        'St. Xaviers Boys Academy',
        'SVDD School Ghatkopar',
        'SVKM JV Parekh International School',
        'Swami Vivekanand English Primary School Chembur',
        'Swami Vivekanand High School, Chembur',
        'Swami Vivekanand International School, Borivalil W (SVIS)',
        'Swami Vivekanand International School, Kandivali W (SVIS)',
        'Swami Vivekanand Pre-Primary School, Chembur',
        'Symbiosis Nursery School',
        'Symbiosis School',
        'Takshashila',
        'Tapovan Vidhyalaya',
        'Thakur International School, Kandivali (W)',
        'Thakur Public School, Kandivali (E)',
        'Thakur Vidya Mandir High school, Kandivali (E)',
        'The Bishops Co-Ed School, Kalyaninagar',
        'The Bishops Co-Ed School, Undri',
        'The Bishops School, Camp',
        'The Dadar Parsee Youth Assembly High School',
        'The Global Mission School',
        'The Green Acres Academy, Chembur',
        'The Green Acres Academy, Mulund',
        'The Kalyani School',
        'The Lexicon International School, Wagholi',
        'The Orbis School, Hadapsar',
        'The Riverside School',
        'The Somaiya School',
        'The Universal School, Tardeo',
        'Tic Tac Toe, Pimple Nilakh',
        'Tree House High School, Karve Road',
        'Tridha',
        'Trinity International School',
        'Udayachal High School',
        'Udayachal Primary School',
        'Udgam School',
        'Universal High (Dahisar)',
        'Universal High (Ghatkopar)',
        'Universal High (Malad)',
        'Utpal Shanghvi Global School',
        'Vasant Vihar High School',
        'Vibgyor High, Balewadi',
        'Vibgyor High, Goregaon',
        'Vibgyor High, Magarpatta',
        'Vibgyor High, Malad (East)',
        'Vibgyor High, NIBM',
        'Vibgyor Roots and Rise',
        'Victorious Kidss Educares',
        'Vidya Valley',
        'Vikhe Patil Memorial School, Lohegaon',
        'Villa Theresa High School',
        'Vivero International',
        'Walsingham House School',
        'Wisdom World school, Hadapsar',
        'Wisdom World School, Wakad',
        'Witty International School, Bangurnagar, Goregaon',
        'Witty International School, Chikoowadi, Borivali',
        'Witty International School, Pawan Baug, Malad',
        'Zydus School For Excellence, Vejalpur',
        'Kangaroo Kids, Malad',
        'C P Goenka International School, Oshiwara (CPGIS)',
        'C P Goenka International School, Thane (CPGIS)',
        'Mansukhbhai Kothari National School (MKNS)',
        'Vibgyor High, Airoli',
        'Universal High (Thane)',
        'Billabong High International School, Andheri',
        'The Shiishyaa School',
        'Swadhyay Bhavan',
        'Vibgyor High, Borivali',
        'Narayana E-Techno School, Nalasopara',
        'Cosmos Castle International School Green Campus',
        'Cosmos Castle International School S.G Road Campus',
        'Global Indian International School, Pune (GIIS)',
        'Shanti Asiatic School, Bopal',
        'The New Tulip International School',
        'Zydus School For Excellence, Godhavi',
        'Rustomjee International School, Dahisar (RIS)',
        'Vibgyor High, Yerwada',
        'New Horizon Scholars School, Thane',
        'Kendriya Vidyalaya No.2 Colaba',
        'Kendriya Vidyalaya No.1 Colaba',
        'Ashoka Universal School, Wadala',
        'Educational Hub',
        'WonderKids PreSchool & Kindergarten',
        'Jindal Vidya Mandir , Salav']
